
exports.model_transmission_type = [
  'Manual'
  'Automatic'
  '4-speed manual'
  '6-speed manual'
  '6-speed automatic'
  '5-speed manual'
  'Single Speed'
  'CVT'
  '7-speed automatic'
  '5-speed shiftable automatic'
  '6-speed automated manual'
  '5-speed automated manual'
  '8-speed shiftable automatic'
  '5-speed automatic'
  '4-speed automatic'
  '6-speed shiftable automatic'
  '7-speed shiftable automatic'
  '7-speed automated manual'
  '8-speed automated manual'
  '8-speed automatic'
  '4-speed shiftable automatic'
  '7-speed manual'
  'Automated Manual'
  'Direct Drive'
  ]