// Generated by CoffeeScript 1.8.0
(function() {
  exports.create = function(data, callback) {
    var md5, md5_gen, password, passwordHash;
    if (data == null) {
      data = {};
    }
    passwordHash = require('password-hash');
    md5 = require('MD5');
    md5_gen = md5(Math.random());
    password = passwordHash.generate(data.password + md5_gen, null, 5);
    UserModel.create({
      email: data.email,
      password: password,
      fio: data.fio,
      phone: data.phone,
      salt: md5_gen
    }, function(error, response) {
      return callback(error, response);
    });
  };

}).call(this);
