// Generated by CoffeeScript 1.8.0
(function() {
  var loadScript;

  module.exports = loadScript = function(req, res, next) {
    res.locals.scripts = ["/js/app.js"];
    res.locals.styles = [];
    next();
  };

}).call(this);
