// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    main: function(req, res) {
      AutoParam.find({
        limit: 1000
      }).populate("model_id", {
        limit: 1000,
        sort: "name"
      }).exec(function(req, result) {
        return res.json(result);
      });
    }
  };

}).call(this);
