// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    main: function(req, res) {
      var client, mc;
      mc = require("mc");
      client = new mc.Client(["127.0.0.1"]);
      return client.connect(function() {
        return console.log("Connected to memcache on four hosts all on port 11211!");
      });
    }
  };

}).call(this);
