// Generated by CoffeeScript 1.8.0

/**
PromoController

@description :: Server-side logic for managing promoes
@help        :: See http://links.sailsjs.org/docs/controllers
 */

(function() {
  module.exports = {
    main: function(req, res) {
      return res.view("promo/main", {
        layout: "layout_promo"
      });
    }
  };

}).call(this);
