// Generated by CoffeeScript 1.8.0

/**
Created by Ihor on 27.09.2014.
 */

(function() {
  module.exports = {
    connection: "someMysqlServer",
    tableName: "auto_vin",
    schema: true,
    autoPK: false,
    autoCreatedAt: false,
    autoUpdatedAt: false,
    attributes: {
      id: {
        type: "integer",
        primaryKey: true,
        autoIncrement: true
      },
      code: {
        type: "string",
        size: 17
      },
      idYear: {
        model: "AutoYear"
      },
      idMake: {
        model: "AutoMake"
      },
      idModel: {
        model: "AutoModel"
      }
    }
  };

}).call(this);
