// Generated by CoffeeScript 1.8.0

/**
AutoMake.js

@description :: TODO: You might write a short summary of how this model works and what it represents here.
@docs        :: http://sailsjs.org/#!documentation/models
 */

(function() {
  module.exports = {
    connection: "someMysqlServer",
    tableName: "auto_make",
    schema: true,
    autoPK: false,
    autoCreatedAt: false,
    autoUpdatedAt: false,
    attributes: {
      id: {
        type: "integer",
        primaryKey: true,
        autoIncrement: true
      },
      name: "string",
      idMake: "integer",
      country: "string",
      make_uid: "string",
      certified: "integer",
      models: {
        collection: "AutoModel",
        via: "id_make"
      },
      params: {
        collection: "AutoParam",
        via: "model_make_id"
      },
      vin: {
        collection: "AutoVin",
        via: "idMake"
      }
    }
  };

}).call(this);
