// Generated by CoffeeScript 1.8.0

/**
User.js

@description :: TODO: You might write a short summary of how this model works and what it represents here.
@docs        :: http://sailsjs.org/#!documentation/models
 */

(function() {
  module.exports = {
    schema: true,
    attributes: {
      name: {
        type: "string",
        required: true
      },
      title: {
        type: "string"
      },
      email: {
        type: "string",
        required: true,
        email: true,
        unique: true
      },
      password: {
        type: "string"
      }
    }
  };

}).call(this);
